apiVersion : apps/v1
kind: Deployment
metadata:
  name: kylejulianpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kylejulianpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: kylejulianpipelinesjavascriptdocker 
    spec:
      containers:
        - name: kylejulianpipelinesjavascriptdocker 
          image: micontenedorregistro.azurecr.io/kylejulianpipelinesjavascriptdocker
          ports:
          - containerPort: 8080